// 檔案路徑: functions/api/defaultData.js

export const defaultData = {
  settings: { cardWidth: 150 },
  categories: [
    { id: "c1", name: "常用", icon: "💚", hidden: false },
    { id: "c2", name: "News (sources)", icon: "📰", hidden: false },
    { id: "c3", name: "Videos & Music", icon: "🎬", hidden: false },
    { id: "c4", name: "工具", icon: "🔧", hidden: false },
    { id: "c5", name: "Email", icon: "📧", hidden: false },
    { id: "c6", name: "AI", icon: "🤖", hidden: false },
    { id: "c7", name: "Photos", icon: "🖼️", hidden: false },
    { id: "c8", name: "安全與密碼", icon: "🔒", hidden: false },
    { id: "c9", name: "Notes & TXT", icon: "📝", hidden: false },
    { id: "c10", name: "Bookmarks", icon: "🔖", hidden: false }
  ],
  items: [
    { id: "a01", catId: "c1", title: "Search", url: "https://s.itools.dedyn.io", desc: "", icon: "", hidden: false },
    { id: "a02", catId: "c1", title: "Google", url: "https://www.google.com/ncr", desc: "", icon: "", hidden: false },
    { id: "a03", catId: "c1", title: "Github", url: "https://github.com", desc: "", icon: "", hidden: false },
    { id: "a04", catId: "c1", title: "CloudFlare", url: "https://www.cloudflare.com", desc: "", icon: "", hidden: false },
    { id: "a05", catId: "c1", title: "ITtools", url: "https://mtools.qzz.io", desc: "", icon: "", hidden: false },
    { id: "a06", catId: "c1", title: "Shorten URL", url: "https://dict.de5.net/", desc: "", icon: "", hidden: false },
    { id: "a07", catId: "c1", title: "GH加速", url: "https://gh.mtools.qzz.io/", desc: "", icon: "", hidden: false },
    { id: "b01", catId: "c2", title: "RSSHUB", url: "https://rss.auto.theworkpc.com/", desc: "", icon: "", hidden: false },
    { id: "b02", catId: "c2", title: "Ahub news", url: "https://ahub.giize.com", desc: "", icon: "", hidden: false },
    { id: "b03", catId: "c2", title: "Buzzing", url: "https://auto.theworkpc.com/", desc: "", icon: "", hidden: false },
    { id: "c01", catId: "c3", title: "Kvideo", url: "https://siumo.de5.net", desc: "", icon: "", hidden: false },
    { id: "c02", catId: "c3", title: "Ouonnki TV", url: "https://tv.auto.theworkpc.com/", desc: "", icon: "", hidden: false },
    { id: "c03", catId: "c3", title: "MoonTV Plus", url: "https://aptv.netlify.app", desc: "有直播", icon: "", hidden: false },
    { id: "c04", catId: "c3", title: "Luna TV", url: "https://tv.res.dedyn.io/", desc: "無直播", icon: "", hidden: false },
    { id: "c05", catId: "c3", title: "MoonTV Plus Vercel", url: "https://m.tvhub.dedyn.io/", desc: "有直播", icon: "", hidden: false },
    { id: "c06", catId: "c3", title: "MoonTV netlify", url: "https://tvagg.netlify.app/", desc: "無直播", icon: "", hidden: false },
    { id: "c07", catId: "c3", title: "Youtube", url: "https://youtube.com", desc: "", icon: "", hidden: false },
    { id: "c08", catId: "c3", title: "TubiTV", url: "https://tubitv.com", desc: "", icon: "", hidden: false },
    { id: "c09", catId: "c3", title: "PlutoTV", url: "https://pluto.tv", desc: "", icon: "", hidden: false },
    { id: "c10", catId: "c3", title: "TV BAK1", url: "https://tv.pack.dedyn.io/", desc: "", icon: "", hidden: false },
    { id: "c11", catId: "c3", title: "TV BAK2", url: "https://hubtv.netlify.app", desc: "https://m.pack.dedyn.io/", icon: "", hidden: false },
    { id: "c12", catId: "c3", title: "Music", url: "https://music.mtools.qzz.io/", desc: "", icon: "", hidden: false },
    { id: "d01", catId: "c4", title: "WebSSH 1", url: "https://webssh-6y5w.onrender.com/", desc: "", icon: "", hidden: false },
    { id: "d02", catId: "c4", title: "ip自查", url: "https://ipfromall.netlify.app/", desc: "", icon: "", hidden: false },
    { id: "d03", catId: "c4", title: "PDF Tools", url: "https://bush.de5.net/en/", desc: "", icon: "", hidden: false },
    { id: "d04", catId: "c4", title: "PDF Tools 2", url: "https://pdfed.pages.dev/en/", desc: "", icon: "", hidden: false },
    { id: "d05", catId: "c4", title: "pdf editor", url: "https://pdf.noad.giize.com", desc: "", icon: "", hidden: false },
    { id: "d06", catId: "c4", title: "Photo Editor", url: "https://edit.pull.dedyn.io/", desc: "", icon: "", hidden: false },
    { id: "d07", catId: "c4", title: "Photo Compress", url: "https://edit.zeabur.app/", desc: "", icon: "", hidden: false },
    { id: "d08", catId: "c4", title: "Converters", url: "https://con.zeabur.app/", desc: "", icon: "", hidden: false },
    { id: "d09", catId: "c4", title: "Uptime Kama", url: "https://uprobot.zeabur.app", desc: "", icon: "", hidden: false },
    { id: "d10", catId: "c4", title: "Edge Sub", url: "https://suv.sirun.gleeze.com/", desc: "", icon: "", hidden: false },
    { id: "d11", catId: "c4", title: "Ultra Sub", url: "https://ultrasub.frii.site/", desc: "", icon: "", hidden: false },
    { id: "d12", catId: "c4", title: "NAT64 Checker", url: "https://pip64.pack.dedyn.io/", desc: "", icon: "", hidden: false },
    { id: "d13", catId: "c4", title: "proxyip checker", url: "https://pip.pack.dedyn.io/", desc: "", icon: "", hidden: false },
    { id: "d14", catId: "c4", title: "online coder", url: "https://onlinecodes.onrender.com", desc: "", icon: "", hidden: false },
    { id: "d15", catId: "c4", title: "NG Projects", url: "https://projectsnav.netlify.app", desc: "", icon: "", hidden: false },
    { id: "d16", catId: "c4", title: "Dev Tools", url: "https://devonline.netlify.app/", desc: "收集国内外优秀设计网站、UI设计资源网站、灵感创意网站、素材资源网站，定时更新分享优质产品设计书签。", icon: "", hidden: false },
    { id: "e01", catId: "c5", title: "Gmail", url: "https://mail.google.com/", desc: "", icon: "", hidden: false },
    { id: "e02", catId: "c5", title: "Outlook", url: "https://outlook.live.com/", desc: "", icon: "", hidden: false },
    { id: "e03", catId: "c5", title: "Proton", url: "https://proton.me/", desc: "", icon: "", hidden: false },
    { id: "e04", catId: "c5", title: "Tuta", url: "https://app.tuta.com/", desc: "", icon: "", hidden: false },
    { id: "e05", catId: "c5", title: "Temp mail 24H", url: "https://tmail.mtools.qzz.io/", desc: "", icon: "", hidden: false },
    { id: "e06", catId: "c5", title: "xyz mail", url: "https://tmail.230603.xyz/", desc: "", icon: "", hidden: false },
    { id: "e07", catId: "c5", title: "cloud mail", url: "https://cmail.mtools.qzz.io/", desc: "", icon: "", hidden: false },
    { id: "f01", catId: "c6", title: "Chat Workers AI", url: "https://chat.siumo.de5.net/", desc: "", icon: "", hidden: false },
    { id: "f02", catId: "c6", title: "tts", url: "https://tts.mtools.qzz.io/", desc: "", icon: "", hidden: false },
    { id: "f03", catId: "c6", title: "text to image 2024", url: "https://aiart.mtools.qzz.io/", desc: "P@ssw0rd", icon: "", hidden: false },
    { id: "f04", catId: "c6", title: "Photo & Docs Com", url: "https://imgdoccompress.onrender.com/", desc: "", icon: "", hidden: false },
    { id: "f05", catId: "c6", title: "Image gen 2025", url: "https://aigen.dogbro.site/", desc: "", icon: "", hidden: false },
    { id: "f06", catId: "c6", title: "Wiki English", url: "https://sirzmkk-chat.hf.space/", desc: "", icon: "", hidden: false },
    { id: "f07", catId: "c6", title: "wiki zh", url: "https://chizk-gpt.hf.space/", desc: "", icon: "", hidden: false },
    { id: "f08", catId: "c6", title: "Translate", url: "https://shatau-translate.hf.space/", desc: "", icon: "", hidden: false },
    { id: "f09", catId: "c6", title: "oepnweb UI smg", url: "https://smgkz-webui.hf.space", desc: "", icon: "", hidden: false },
    { id: "f10", catId: "c6", title: "open gpt", url: "https://derekib-coding.hf.space/", desc: "", icon: "", hidden: false },
    { id: "f11", catId: "c6", title: "coder", url: "https://inchey-coder.hf.space/", desc: "", icon: "", hidden: false },
    { id: "g01", catId: "c7", title: "Funny Bar", url: "https://funnybar.netlify.app/", desc: "", icon: "", hidden: false },
    { id: "g02", catId: "c7", title: "sport images", url: "https://cftgimgbed.pages.dev/", desc: "", icon: "", hidden: false },
    { id: "g03", catId: "c7", title: "No-mask downloader", url: "https://no.pack.dedyn.io/", desc: "", icon: "", hidden: false },
    { id: "h01", catId: "c8", title: "NodeWarden", url: "https://safe.transf.workers.dev", desc: "", icon: "", hidden: false },
    { id: "h02", catId: "c8", title: "doh worker", url: "https://noop.de5.net", desc: "z", icon: "", hidden: false },
    { id: "i01", catId: "c9", title: "Situ note", url: "https://target.de5.net", desc: "", icon: "", hidden: false }
  ]
};
